import type { Metadata } from "next";
import styles from "./page.module.css";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Wyrd Studios privacy policy. We collect minimal data. Our apps collect none.",
};

export default function PrivacyPage() {
  return (
    <main>
      <section className={styles.hero}>
        <div className="container">
          <p className={styles.eyebrow}>Legal</p>
          <h1 className={styles.headline}>Privacy Policy</h1>
          <p className={styles.meta}>
            Effective Date: March 15, 2026 &nbsp;·&nbsp; Last Updated: March 15, 2026
          </p>
        </div>
      </section>

      <section className={styles.section}>
        <div className={`container container--content ${styles.content}`}>

          <div className={styles.summary}>
            <h2>The short version</h2>
            <p>
              Our apps don&apos;t collect personal data. Our website doesn&apos;t set tracking
              cookies or build profiles on visitors. The only personal data that touches
              our systems is what you voluntarily send us through our contact form — and
              even that is handled by a third-party service, not stored by us directly.
            </p>
          </div>

          <h2>Who we are</h2>
          <p>
            Wyrd Studios is an independent app studio. We make small Android apps —
            embyrn, flyaway, and Sequence Timer — and operate a marketing website at
            wyrdstudios.dev. You can reach us at{" "}
            <a href="mailto:hello@wyrdstudios.dev">hello@wyrdstudios.dev</a>.
          </p>

          <h2>Our website (wyrdstudios.dev)</h2>

          <h3>What we don&apos;t do</h3>
          <p>
            We do not use advertising trackers, analytics services, or marketing pixels
            on wyrdstudios.dev. We do not set cookies for tracking or profiling purposes.
            We do not sell, share, or monetize visitor data in any form.
          </p>

          <h3>What happens when you visit</h3>
          <p>
            Our website is hosted on Cloudflare Pages. Like all web servers, Cloudflare
            may automatically log standard technical information when your browser loads
            a page — things like your IP address, browser type, and the time of your
            request. This is infrastructure-level logging that Cloudflare handles for
            security and performance purposes; it is not something we configure, collect,
            or have direct access to. Cloudflare&apos;s own privacy policy governs how they
            handle this data.
          </p>

          <h3>Contact form</h3>
          <p>
            If you submit our contact form, you&apos;ll provide your name, email address,
            and a message. That information is sent directly to Formspree, a third-party
            form processing service, which delivers it to our inbox. We use this
            information only to respond to your inquiry. We do not add contact form
            submissions to mailing lists or use them for marketing.
          </p>

          <h2>Our Android apps</h2>

          <h3>What we don&apos;t collect</h3>
          <p>
            Our apps — embyrn, flyaway, and Sequence Timer — do not collect personal
            data. They do not use analytics, crash reporting services, advertising SDKs,
            or any other third-party data collection tools. They do not require an
            account or login. They do not transmit information about you or your device
            to our servers or to any third party.
          </p>

          <h3>What stays on your device</h3>
          <p>
            Any data generated by our apps (such as a saved timer configuration in
            Sequence Timer, a trip itinerary in flyaway, or pet state in embyrn) exists
            only on your device. We cannot see it, access it, or recover it if you
            uninstall the app or lose your device.
          </p>

          <h3>App permissions</h3>
          <p>
            Any Android permissions our apps request are used solely for the app&apos;s
            core functionality and are not used to collect data about you. You can review
            and revoke permissions at any time through your Android device settings.
          </p>

          <h2>Cookies</h2>
          <p>
            We do not use cookies for tracking, analytics, or advertising. Cloudflare
            may set a limited technical cookie (such as a security challenge cookie) as
            part of its standard protection infrastructure. These are functional in
            nature and governed by Cloudflare&apos;s privacy policy.
          </p>

          <h2>Children&apos;s privacy</h2>
          <p>
            Our apps are general-audience apps not directed at children under 13. We do
            not knowingly collect personal information from anyone. If you are a parent
            or guardian and believe your child has submitted personal information to us,
            please contact us at{" "}
            <a href="mailto:hello@wyrdstudios.dev">hello@wyrdstudios.dev</a>.
          </p>

          <h2>Your rights</h2>
          <p>
            Because we collect very little personal data, there is not much to act on
            — but your rights still apply.
          </p>
          <p>
            If you have submitted our contact form and would like to request deletion of
            that message, contact us at{" "}
            <a href="mailto:hello@wyrdstudios.dev">hello@wyrdstudios.dev</a> and we will
            address it promptly.
          </p>
          <p>
            If you are located in the European Union or European Economic Area, you have
            rights under the GDPR, including the right to access, correct, or delete
            personal data we hold about you. To exercise any GDPR rights, contact us at{" "}
            <a href="mailto:hello@wyrdstudios.dev">hello@wyrdstudios.dev</a>.
          </p>

          <h2>Data security</h2>
          <p>
            We take reasonable precautions to protect any data we handle. Our website
            uses HTTPS. We do not store payment information or sensitive personal data.
          </p>

          <h2>Changes to this policy</h2>
          <p>
            If we change our data practices in a meaningful way, we will update this
            policy and revise the &ldquo;Last Updated&rdquo; date above. For significant changes,
            we will make a reasonable effort to notify users — for example, through an
            in-app notice or a post on our website.
          </p>

          <h2>Contact</h2>
          <p>Questions, concerns, or data requests:</p>
          <p>
            <strong>Email:</strong>{" "}
            <a href="mailto:hello@wyrdstudios.dev">hello@wyrdstudios.dev</a>
            <br />
            <strong>Website:</strong> wyrdstudios.dev
          </p>

        </div>
      </section>
    </main>
  );
}
